<?php

namespace Database\Seeders;

use App\Models\Azienda;
use App\Models\Resources\Coupon;
use App\Models\Resources\Faq;
use App\Models\Resources\Promozione;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('utente')->insert([
            [
                'username' => 'adminadmin',
                'password' => Hash::make('JmoxlJ1q'),
                'livello' => 'admin',
                'created_at' => now(),
                'updated_at' => now(),
                'nome' => null,
                'cognome' => null,
                'genere' => null,
                'eta' => null,
                'email' => null,
                'telefono' => null,
            ],
            [
                'username' => 'staffstaff',
                'password' => Hash::make('JmoxlJ1q'),
                'nome' => 'Mario',
                'cognome' => 'Rossi',
                'livello' => 'staff',
                'created_at' => now(),
                'updated_at' => now(),
                'genere' => null,
                'eta' => null,
                'email' => null,
                'telefono' => null,
            ],
            [
                'username' => 'useruser',
                'password' => Hash::make('JmoxlJ1q'),
                'nome' => 'Luca',
                'cognome' => 'Verdi',
                'livello' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
                'genere' => 'M',
                'eta' => 21,
                'email' => 'luca@verdi.it',
                'telefono' => '3333333333',
            ]
        ]);

        DB::table('faq')->insert([
            [
                'idUtente' => 1,
                'titolo' => 'Come funziona il riscatto dei coupon sul sito?',
                'descrizione' => 'Per riscattare un coupon sul nostro sito, devi essere registrato e aver effettuato l\'accesso al tuo account. Una volta trovato il coupon desiderato, fai clic sul pulsante di riscatto e il coupon verrà aggiunto al tuo profilo. Ricorda che ogni coupon può essere riscattato una sola volta per utente.'
            ],
            [
                'idUtente' => 1,
                'titolo' => 'Posso riscattare più volte lo stesso coupon?',
                'descrizione' => 'No, ogni coupon può essere riscattato una sola volta per utente. Una volta che hai riscattato un coupon e lo hai aggiunto al tuo profilo, non sarà più possibile riscattarlo nuovamente.'
            ],
            [
                'idUtente' => 1,
                'titolo' => 'Dove posso trovare i coupon che ho già riscattato?',
                'descrizione' => 'Tutti i coupon che hai riscattato saranno visibili nella sezione del tuo profilo. Accedi al tuo account e vai alla sezione "Coupon riscattati" per visualizzare l\'elenco completo dei coupon che hai già utilizzato.'
            ],
            [
                'idUtente' => 1,
                'titolo' => 'Posso condividere i coupon riscattati con altre persone?',
                'descrizione' => 'I coupon riscattati sono strettamente personali e non possono essere condivisi con altre persone. Ogni utente può riscattare e utilizzare i propri coupon, ma non è possibile trasferirli o condividerli con altri utenti.'
            ],
            [
                'idUtente' => 1,
                'titolo' => 'Come posso modificare i miei dati personali?',
                'descrizione' => 'Per modificare i tuoi dati personali, accedi al tuo account e vai alla sezione "Profilo". Qui potrai modificare i tuoi dati personali e aggiornarli.'
            ],
            [
                'idUtente' => 1,
                'titolo' => 'Dove possono essere utilizzati i coupon riscattati?',
                'descrizione' => 'I coupon riscattati potranno essere presso il punto vendita indicato nel coupon. Per maggiori informazioni, consulta la descrizione della promozione.'
            ]
        ]);

        DB::table('azienda')->insert([
            [
                'idUtente' => 1,
                'visibile' => true,
                'nome' => 'Apple',
                'via' => 'Via dei Giardini',
                'numero_civico' => 10,
                'citta' => 'Milano',
                'cap' => '20100',
                'logo' => 'apple.svg',
                'ragione_sociale' => 'Inc.',
                'descrizione' => 'Apple Inc. è un\'azienda statunitense che produce dispositivi e software. È conosciuta principalmente per i suoi prodotti come iPhone, iPad, Mac e Apple Watch. Apple è nota per il design innovativo, l\'elevata qualità e l\'ecosistema integrato che offre ai suoi utenti. Con sede a Cupertino, California, Apple è diventata una delle aziende più influenti nel settore della tecnologia.',
                'tipologia' => 'Tecnologia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idUtente' => 1,
                'visibile' => true,
                'nome' => 'Samsung',
                'via' => 'Via Roma',
                'numero_civico' => 20,
                'citta' => 'Roma',
                'cap' => '00100',
                'logo' => 'samsung.svg',
                'ragione_sociale' => 'Corporation',
                'descrizione' => 'Samsung è un\'azienda sudcoreana specializzata nella produzione di dispositivi elettronici. Offre una vasta gamma di prodotti tra cui smartphone, tablet, televisori, elettrodomestici e componenti per computer. Samsung è nota per la sua innovazione tecnologica, la qualità dei suoi prodotti e la sua presenza globale. È uno dei principali concorrenti di Apple nel settore della tecnologia.',
                'tipologia' => 'Tecnologia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idUtente' => 1,
                'visibile' => true,
                'nome' => 'OnePlus',
                'via' => 'Via Venezia',
                'numero_civico' => 30,
                'citta' => 'Firenze',
                'cap' => '50100',
                'logo' => 'oneplus.svg',
                'ragione_sociale' => 'Technology',
                'descrizione' => 'OnePlus è un produttore cinese di smartphone di alta qualità. L\'azienda si è guadagnata una reputazione per offrire dispositivi con specifiche tecniche avanzate a un prezzo competitivo. I telefoni OnePlus sono noti per le loro prestazioni eccellenti, il design elegante e l\'interfaccia utente personalizzata basata su Android chiamata OxygenOS. OnePlus ha sviluppato una base di fan fedeli grazie alla sua combinazione di valore e qualità.',
                'tipologia' => 'Tecnologia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idUtente' => 1,
                'visibile' => true,
                'nome' => 'Logitech',
                'via' => 'Via Garibaldi',
                'numero_civico' => 40,
                'citta' => 'Torino',
                'cap' => '10100',
                'logo' => 'logitech.svg',
                'ragione_sociale' => 'Inc.',
                'descrizione' => 'Logitech è un\'azienda svizzera specializzata nella produzione di periferiche informatiche. Offre una vasta gamma di prodotti tra cui tastiere, mouse, altoparlanti, webcam e molto altro. Logitech è conosciuta per la qualità e l\'innovazione delle sue periferiche, che sono utilizzate sia dagli utenti domestici che dai professionisti. Grazie alla sua esperienza e alla sua reputazione, Logitech è diventata un marchio di riferimento nel settore delle periferiche informatiche.',
                'tipologia' => 'Tecnologia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idUtente' => 1,
                'visibile' => true,
                'nome' => 'Corsair',
                'via' => 'Via Cavour',
                'numero_civico' => 50,
                'citta' => 'Napoli',
                'cap' => '80100',
                'logo' => 'corsair.svg',
                'ragione_sociale' => 'Corporation',
                'descrizione' => 'Corsair è un\'azienda statunitense specializzata nella produzione di componenti e periferiche per computer. Offre una vasta gamma di prodotti destinati ai giocatori e agli appassionati di PC, tra cui tastiere, mouse, schede grafiche, alimentatori e molto altro. Corsair è conosciuta per la qualità e le prestazioni dei suoi prodotti, che sono spesso scelti dai giocatori professionisti e dagli overclocker. L\'azienda ha costruito una solida reputazione nel settore dei componenti per computer di alta qualità.',
                'tipologia' => 'Tecnologia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idUtente' => 1,
                'visibile' => true,
                'nome' => 'HP',
                'via' => 'Via Dante',
                'numero_civico' => 60,
                'citta' => 'Bologna',
                'cap' => '40100',
                'logo' => 'hp.svg',
                'ragione_sociale' => 'HP Inc.',
                'descrizione' => 'HP, acronimo di Hewlett-Packard, è un\'azienda statunitense che produce dispositivi e software. Offre una vasta gamma di prodotti tra cui stampanti, computer portatili, desktop, workstation e molto altro. HP è conosciuta per la sua lunga storia di innovazione e qualità. I suoi prodotti sono ampiamente utilizzati sia a livello domestico che aziendale. HP è uno dei principali attori nel settore della tecnologia e fornisce soluzioni per le esigenze informatiche di milioni di persone in tutto il mondo.',
                'tipologia' => 'Tecnologia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idUtente' => 1,
                'visibile' => true,
                'nome' => 'Conad',
                'via' => 'Via Mazzini',
                'numero_civico' => 70,
                'citta' => 'Genova',
                'cap' => '16100',
                'logo' => 'conad.svg',
                'ragione_sociale' => 'S.p.A.',
                'descrizione' => 'Conad è una catena italiana di supermercati che offre una vasta selezione di prodotti alimentari e non alimentari. I negozi Conad sono presenti in tutto il paese e offrono un\'ampia scelta di prodotti di alta qualità a prezzi competitivi. Conad si impegna a soddisfare le esigenze dei suoi clienti offrendo una combinazione di prodotti freschi, convenienza e servizio eccellente. È diventato un punto di riferimento per gli acquisti quotidiani degli italiani.',
                'tipologia' => 'Alimentari',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idUtente' => 1,
                'visibile' => true,
                'nome' => 'Crai',
                'via' => 'Via Matteotti',
                'numero_civico' => 80,
                'citta' => 'Verona',
                'cap' => '37100',
                'logo' => 'crai.svg',
                'ragione_sociale' => 'S.p.A.',
                'descrizione' => 'Crai è una catena italiana di supermercati che si concentra sulla qualità e l\'autenticità dei prodotti. I negozi Crai offrono una vasta selezione di alimentari freschi, prodotti locali, vini e molto altro. L\'azienda si impegna a sostenere i produttori locali e a offrire prodotti di alta qualità ai suoi clienti. Grazie alla sua attenzione per la qualità e alla sua presenza diffusa sul territorio, Crai è diventato un punto di riferimento per gli acquirenti che cercano prodotti autentici.',
                'tipologia' => 'Alimentari',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idUtente' => 1,
                'visibile' => true,
                'nome' => 'Esselunga',
                'via' => 'Via Garibaldi',
                'numero_civico' => 90,
                'citta' => 'Milano',
                'cap' => '20100',
                'logo' => 'esselunga.png',
                'ragione_sociale' => 'S.p.A.',
                'descrizione' => 'Esselunga è una catena italiana di supermercati che si distingue per la qualità dei suoi prodotti e il servizio ai clienti. I negozi Esselunga offrono una vasta gamma di prodotti alimentari, bevande, prodotti per la casa e altro ancora. L\'azienda ha una forte attenzione per l\'eccellenza dei prodotti, la sostenibilità e l\'innovazione. Esselunga è un marchio di fiducia per molti consumatori italiani che cercano qualità e convenienza.',
                'tipologia' => 'Alimentari',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idUtente' => 1,
                'visibile' => true,
                'nome' => 'Si con te',
                'via' => 'Via Roma',
                'numero_civico' => 100,
                'citta' => 'Roma',
                'cap' => '00100',
                'logo' => 'si_con_te.png',
                'ragione_sociale' => 'S.p.A.',
                'descrizione' => 'Si con te è una catena italiana di supermercati che si impegna a offrire prodotti sani e di qualità. I negozi Si con te mettono al centro il benessere dei clienti, offrendo una vasta selezione di prodotti biologici, senza glutine e adatti a diverse esigenze dietetiche. L\'azienda si impegna anche in iniziative di responsabilità sociale e sostenibilità ambientale. Si con te è una scelta ideale per coloro che cercano prodotti alimentari salutari e sostenibili.',
                'tipologia' => 'Alimentari',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idUtente' => 1,
                'visibile' => true,
                'nome' => 'Auchan',
                'via' => 'Via Torino',
                'numero_civico' => 110,
                'citta' => 'Milano',
                'cap' => '20100',
                'logo' => 'auchan.svg',
                'ragione_sociale' => 'S.p.A.',
                'descrizione' => 'Auchan è una catena internazionale di ipermercati che offre una vasta selezione di prodotti alimentari e non alimentari. I negozi Auchan si distinguono per la loro ampiezza e la varietà di prodotti disponibili. L\'azienda si impegna a offrire prezzi competitivi e una buona esperienza di shopping ai suoi clienti. Auchan è presente in diversi paesi ed è un marchio riconosciuto a livello globale nel settore della grande distribuzione.',
                'tipologia' => 'Alimentari',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idUtente' => 1,
                'visibile' => true,
                'nome' => 'Carrefour',
                'via' => 'Via Garibaldi',
                'numero_civico' => 120,
                'citta' => 'Torino',
                'cap' => '10100',
                'logo' => 'carrefour.svg',
                'ragione_sociale' => 'S.p.A.',
                'descrizione' => 'Carrefour è una catena internazionale di supermercati che offre una vasta gamma di prodotti alimentari, prodotti per la casa, elettronica e molto altro. L\'azienda è impegnata nella promozione di uno stile di vita sano e sostenibile, offrendo una selezione di prodotti biologici, a basso impatto ambientale e di qualità. Carrefour si distingue anche per il suo impegno sociale e ambientale attraverso diverse iniziative. È un marchio di fiducia per milioni di consumatori in tutto il mondo.',
                'tipologia' => 'Alimentari',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idUtente' => 1,
                'visibile' => true,
                'nome' => 'Adidas',
                'via' => 'Via della Vittoria',
                'numero_civico' => 130,
                'citta' => 'Firenze',
                'cap' => '50100',
                'logo' => 'adidas.svg',
                'ragione_sociale' => 'AG',
                'descrizione' => 'Adidas è un\'azienda tedesca specializzata nella produzione di abbigliamento sportivo, calzature e accessori. L\'azienda è famosa per il suo design innovativo, la qualità dei suoi prodotti e la presenza di celebrità e atleti di fama mondiale come testimonial. Adidas offre una vasta gamma di prodotti per diverse attività sportive e lifestyle. È un marchio iconico nel settore della moda sportiva e un punto di riferimento per gli appassionati di sport e stile di tutto il mondo.',
                'tipologia' => 'Moda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idUtente' => 1,
                'visibile' => true,
                'nome' => 'Nike',
                'via' => 'Via Milano',
                'numero_civico' => 140,
                'citta' => 'Roma',
                'cap' => '00100',
                'logo' => 'nike.svg',
                'ragione_sociale' => 'Inc.',
                'descrizione' => 'Nike è un\'azienda statunitense specializzata nella produzione di abbigliamento, calzature e accessori sportivi. È uno dei marchi più riconoscibili e influenti nel settore della moda sportiva. Nike offre una vasta gamma di prodotti per diverse discipline sportive, combinando innovazione tecnologica e design di tendenza. L\'azienda è nota per la sua partnership con numerosi atleti di fama mondiale e per il suo impegno per la sostenibilità ambientale. Nike rappresenta uno stile di vita attivo e dinamico.',
                'tipologia' => 'Moda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idUtente' => 1,
                'visibile' => true,
                'nome' => 'Obey',
                'via' => 'Via Garibaldi',
                'numero_civico' => 150,
                'citta' => 'Milano',
                'cap' => '20100',
                'logo' => 'obey.svg',
                'ragione_sociale' => 'Clothing',
                'descrizione' => 'Obey è un marchio di abbigliamento e accessori con sede negli Stati Uniti. Fondata dal famoso artista di street art Shepard Fairey, Obey è conosciuta per il suo stile unico e audace. Il marchio si ispira alla cultura urbana e alla politica, creando design distintivi che riflettono l\'individualità e l\'attitudine dei suoi clienti.',
                'tipologia' => 'Moda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idUtente' => 1,
                'visibile' => true,
                'nome' => 'Vans',
                'via' => 'Via Roma',
                'numero_civico' => 160,
                'citta' => 'Roma',
                'cap' => '00100',
                'logo' => 'vans.png',
                'ragione_sociale' => 'Inc.',
                'descrizione' => 'Vans è un\'azienda americana di calzature e abbigliamento con un focus particolare sullo skateboarding e lo stile di vita giovanile. Vans è famosa per le sue iconiche scarpe da skate, come le Vans Authentic e le Vans Old Skool, ma offre anche una vasta gamma di abbigliamento e accessori di tendenza. Il marchio si distingue per il suo spirito di libertà, creatività e autenticità.',
                'tipologia' => 'Moda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idUtente' => 1,
                'visibile' => true,
                'nome' => 'Zara',
                'via' => 'Via Garibaldi',
                'numero_civico' => 170,
                'citta' => 'Milano',
                'cap' => '20100',
                'logo' => 'zara.svg',
                'ragione_sociale' => 'S.p.A.',
                'descrizione' => 'Zara è una catena di negozi di abbigliamento spagnola nota per la sua moda veloce e accessibile. L\'azienda offre una vasta gamma di abbigliamento, calzature e accessori per uomo, donna e bambini. Zara si distingue per il suo design di tendenza, la qualità dei suoi prodotti e la sua capacità di rispondere rapidamente alle ultime tendenze di moda. Con negozi presenti in tutto il mondo, Zara è diventato un marchio di moda globale apprezzato da molti consumatori.',
                'tipologia' => 'Moda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idUtente' => 1,
                'visibile' => true,
                'nome' => 'Puma',
                'via' => 'Via Venezia',
                'numero_civico' => 180,
                'citta' => 'Firenze',
                'cap' => '50100',
                'logo' => 'puma.svg',
                'ragione_sociale' => 'SE',
                'descrizione' => 'Puma è un\'azienda tedesca di abbigliamento sportivo che offre una varietà di prodotti, inclusi abbigliamento, calzature e accessori per diverse discipline sportive. Puma è famosa per il suo design innovativo e il suo impegno verso l\'alto prestazioni. L\'azienda è sponsor di numerosi atleti e squadre sportive, e si dedica a promuovere uno stile di vita attivo e dinamico.',
                'tipologia' => 'Moda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('promozione')->insert([
            [
                'idAzienda' => 1,
                'titolo' => 'APPLE iPhone 14 128GB Mezzanotte',
                'descrizione' => 'L\'iPhone 14 è l\'ultima innovazione di Apple nel mondo degli smartphone. Questo straordinario dispositivo incarna l\'eccellenza tecnologica e il design elegante che hanno reso famoso l\'iPhone. Con una combinazione di potenza, funzionalità e stile, l\'iPhone 14 ridefinisce l\'esperienza utente e porta l\'utilizzo degli smartphone a un livello superiore.',
                'immagine' => 'iphone_14.webp',
                'modalita' => 'Online',
                'luogo' => 'Tutti gli apple store online',
                'inizio' => now(),
                'fine' => now()->addDays(30),
                'sconto' => 'percentuale',
                'valore_sconto' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAzienda' => 1,
                'titolo' => 'APPLE Watch Ultra GPS + Cellular, 49mm Cassa in titanio con Trail Loop giallo/beige - S/M',
                'descrizione' => 'L\'Apple Watch è un orologio intelligente di alta qualità che unisce stile, funzionalità e tecnologia avanzata. Con il suo design elegante e raffinato, l\'Apple Watch è il compagno perfetto per chi desidera tenere il polso al passo con il progresso tecnologico. Dotato di un display retina luminoso e nitido, l\'Apple Watch offre una chiara visualizzazione delle informazioni, delle notifiche e delle applicazioni. Puoi personalizzare il quadrante dell\'orologio con una vasta gamma di sfondi, complicazioni e stili, per adattarlo al tuo stile personale e alle tue esigenze.',
                'immagine' => 'apple_watch.webp',
                'modalita' => 'Online',
                'luogo' => 'Tutti gli apple store online',
                'inizio' => now()->subDays(2),
                'fine' => now()->addDays(14),
                'sconto' => 'prezzo_fisso',
                'valore_sconto' => '899.99',
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'idAzenda' => 2,
                'titolo' => 'Galaxy S23 Ultra Silicone Grip Case',
                'descrizione' => 'La custodia in silicone Grip Case è progettata per offrire una protezione completa al tuo Galaxy S23 Ultra. La custodia è realizzata in silicone di alta qualità, che offre una presa sicura e una protezione ottimale contro urti e graffi. La custodia è disponibile in una varietà di colori vivaci, per adattarsi al tuo stile personale.',
                'immagine' => 'cover_s23.avif',
                'modalita' => 'Negozio',
                'luogo' => 'Tutti i negozi Samsung',
                'inizio' => now()->subDays(5),
                'fine' => now()->addDays(12),
                'sconto' => 'quantita',
                'valore_sconto' => '2x1',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'idAzenda' => 2,
                'titolo' => 'Neo QLED 4K 43" QN90B TV 2022',
                'descrizione' => 'Il Neo QLED 4K 43" QN90B TV 2022 è un televisore di alta qualità che offre una straordinaria esperienza di visione. Il Neo QLED 4K 43" QN90B TV 2022 è dotato di un display QLED 4K, che offre una qualità dell\'immagine eccezionale. Il Neo QLED 4K 43" QN90B TV 2022 è dotato di un processore Quantum 4K, che offre una qualità dell\'immagine eccezionale. Il Neo QLED 4K 43" QN90B TV 2022 è dotato di un processore Quantum 4K, che offre una qualità dell\'immagine eccezionale. Il Neo QLED 4K 43" QN90B TV 2022 è dotato di un processore Quantum 4K, che offre una qualità dell\'immagine eccezionale.',
                'immagine' => 'neo_tv.avif',
                'modalita' => 'Online',
                'luogo' => 'Store online Samsung',
                'inizio' => now()->subDays(7),
                'fine' => now()->addDays(12),
                'sconto' => 'prezzo_fisso',
                'valore_sconto' => '799,00',
                'created_at' => now()->subDays(8),
                'updated_at' => now()->subDays(8),
            ],
            [
                'idAzenda' => 3,
                'titolo' => 'OnePlus 11 5G',
                'descrizione' => 'Il OnePlus 11 5G è uno smartphone di alta qualità che offre una straordinaria esperienza utente. Il OnePlus 11 5G è dotato di un display AMOLED da 6,55 pollici, che offre una qualità dell\'immagine eccezionale. Il OnePlus 11 5G è dotato di un processore Snapdragon 888, che offre prestazioni eccezionali. Il OnePlus 11 5G è dotato di una fotocamera principale da 50 MP, che offre una qualità dell\'immagine eccezionale. Il OnePlus 11 5G è dotato di una batteria da 4500 mAh, che offre un\'autonomia eccezionale.',
                'immagine' => 'oneplus_11.png',
                'modalita' => 'Online',
                'luogo' => 'Store online OnePlus',
                'inizio' => now()->addDays(5),
                'fine' => now()->addDays(20),
                'sconto' => 'prezzo_fisso',
                'valore_sconto' => '849,00',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'idAzenda' => 3,
                'titolo' => 'OnePlus 10T 5G 3D Tempered Glass Screen Protector Black',
                'descrizione' => 'Il OnePlus 10T 5G 3D Tempered Glass Screen Protector Black è un accessorio protettivo progettato specificamente per il OnePlus 10T 5G. Realizzato con vetro temperato 3D di alta qualità, offre una protezione affidabile per lo schermo del tuo dispositivo da graffi, urti e sporco.',
                'immagine' => 'glass.png',
                'modalita' => 'Negozio',
                'luogo' => 'Tutti i negozi OnePlus',
                'inizio' => now()->subDays(3),
                'fine' => now()->addDays(18),
                'sconto' => 'quantita',
                'valore_sconto' => '3x2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAzenda' => 4,
                'titolo' => 'G502 HERO',
                'descrizione' => 'Design iconico G502 e wireless LIGHTSPEED per una connettività ultraveloce e affidabile. Il sensore HERO 25K offre tracciamento submicrometrico. Compatibile con POWERPLAY per il caricamento continuo, a riposo o durante il gioco.',
                'immagine' => 'g502.png',
                'modalita' => 'Online',
                'luogo' => 'Store online Logitech',
                'inizio' => now(),
                'fine' => now()->addDays(15),
                'sconto' => 'prezzo_fisso',
                'valore_sconto' => '49,99',
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'idAzenda' => 4,
                'titolo' => 'Volante G923',
                'descrizione' => 'Volante da corsa TRUEFORCE per Xbox, Playstation e PC',
                'immagine' => 'g923.png',
                'modalita' => 'Negozio',
                'luogo' => 'Tutti i negozi Logitech',
                'inizio' => now()->subDays(2),
                'fine' => now()->addDays(16),
                'sconto' => 'percentuale',
                'valore_sconto' => 25,
                'created_at' => now()->subDays(4),
                'updated_at' => now()->subDays(4),
            ],
            [
                'idAzenda' => 5,
                'titolo' => 'Monitor gaming CORSAIR XENEON 32QHD165',
                'descrizione' => 'Con CORSAIR XENEON, giochi e contenuti multimediali prendono vita grazie a un display IPS QHD (2560 x 1440) da 32 pollici, brillante e ultrasottile, che offre una frequenza di aggiornamento fino a 165 Hz e tempi di risposta di 1 ms.',
                'immagine' => '32qhd165.png',
                'modalita' => 'Online',
                'luogo' => 'Store online Corsair',
                'inizio' => now()->subDays(3),
                'fine' => now()->addDays(18),
                'sconto' => 'prezzo_fisso',
                'valore_sconto' => '399,99',
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3),
            ],
            [
                'idAzenda' => 5,
                'titolo' => 'Kit pasta termica ad alte prestazioni XTM50',
                'descrizione' => 'La pasta termica ad alte prestazioni CORSAIR XTM50 è la soluzione più completa per aiutare ad abbassare le temperature dei componenti del PC ed evitare che questo si surriscaldi anche quando viene utilizzato al massimo delle prestazioni.',
                'immagine' => 'xtm50.png',
                'modalita' => 'Negozio',
                'luogo' => 'Tutti i negozi Corsair',
                'inizio' => now()->subDays(3),
                'fine' => now()->addDays(13),
                'sconto' => 'quantita',
                'valore_sconto' => '2x1',
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3)
            ],
            [
                'idAzenda' => 6,
                'titolo' => 'Confezione da 2 cartucce d\'inchiostro nero/tricromia originali HP 302',
                'descrizione' => 'La confezione da 2 cartucce d\'inchiostro nero/tricromia originali HP 302 offre una soluzione pratica per la stampa di alta qualità. Progettate specificamente per le stampanti HP, queste cartucce garantiscono stampe nitide e brillanti con colori vivaci e testo nitido. Con una confezione da due, avrai abbastanza inchiostro per affrontare le tue esigenze di stampa quotidiane.',
                'immagine' => 'hp302.png',
                'modalita' => 'Online',
                'luogo' => 'Store online HP',
                'inizio' => now(),
                'fine' => now()->addDays(15),
                'sconto' => 'quantita',
                'valore_sconto' => '2x1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAzenda' => 6,
                'titolo' => 'Stampante multifunzione HP ENVY Inspire 7221e',
                'descrizione' => 'La stampante multifunzione HP ENVY Inspire 7221e è un dispositivo versatile progettato per soddisfare le esigenze di stampa, scansione e copia degli utenti domestici e dei piccoli uffici. Questo modello combina funzionalità avanzate con un design elegante e compatto.',
                'immagine' => 'stampante.png',
                'modalita' => 'Negozio',
                'luogo' => 'Tutti i negozi HP',
                'inizio' => now()->addDays(5),
                'fine' => now()->addDays(25),
                'sconto' => 'prezzo_fisso',
                'valore_sconto' => '99,99',
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2)
            ],
            [
                'idAzenda' => 7,
                'titolo' => 'Caffè Macinato Qualità Classica 2 x 250 g Conad',
                'descrizione' => 'Il Caffè Macinato Qualità Classica di Conad è un blend pregiato di chicchi di caffè selezionati, dal gusto intenso e avvolgente. Confezionato in pratiche confezioni da 250 g ciascuna, offre una fragranza avvolgente e una crema densa e persistente. Ideale per gli amanti del caffè tradizionale, questo prodotto ti permette di gustare un espresso di alta qualità direttamente a casa tua.',
                'immagine' => 'caffe.png',
                'modalita' => 'Online',
                'luogo' => 'Store online Conad',
                'inizio' => now()->subDays(3),
                'fine' => now()->addDays(18),
                'sconto' => 'prezzo_fisso',
                'valore_sconto' => '2,99',
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3),
            ],
            [
                'idAzenda' => 7,
                'titolo' => 'Pedigree Dentastix Chewy Chunx Snack Cane Gusto Pollo 5-15kg 68 g',
                'descrizione' => 'Pedigree Dentastix Chewy Chunx Snack sono deliziosi bocconcini per cani di taglia media (5-15 kg) con gusto pollo. Questi snack sono progettati per aiutare a mantenere la bocca del tuo cane sana, grazie alla loro consistenza morbida che aiuta a ridurre la formazione del tartaro. Sono un\'ottima opzione per una ricompensa gustosa e allo stesso tempo benefica per l\'igiene dentale del tuo fedele amico a quattro zampe.',
                'immagine' => 'dentastix.png',
                'modalita' => 'Negozio',
                'luogo' => 'Tutti i negozi Conad',
                'inizio' => now()->subDays(5),
                'fine' => now()->addDays(20),
                'sconto' => 'quantita',
                'valore_sconto' => '3x2',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5)
            ],
            [
                'idAzenda' => 8,
                'titolo' => 'Mele Fuji Crai',
                'descrizione' => 'Le mele Fuji Crai sono mele di alta qualità, coltivate con cura per offrire una dolcezza e un gusto unici. Con la loro pelle sottile e croccante e la polpa succosa, queste mele sono perfette per essere gustate da sole o utilizzate in ricette dolci e salate. Le mele Fuji Crai sono una scelta deliziosa e sana per soddisfare la tua voglia di frutta fresca e gustosa.',
                'immagine' => 'mele.png',
                'modalita' => 'Online',
                'luogo' => 'Store online Crai',
                'inizio' => now()->subDays(3),
                'fine' => now()->addDays(18),
                'sconto' => 'prezzo_fisso',
                'valore_sconto' => '1,99',
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3),
            ],
            [
                'idAzenda' => 8,
                'titolo' => 'Raid Mosche e Zanzare Plus, 400 ml',
                'descrizione' => 'Il Raid Mosche e Zanzare Plus è un potente aerosol progettato per proteggere la tua casa dagli insetti volanti. Con la sua formula avanzata, combatte efficacemente mosche, zanzare e altri fastidiosi insetti, offrendo una protezione duratura. Con una capacità di 400 ml, è ideale per l\'uso domestico e fornisce una soluzione rapida e conveniente per liberarsi degli insetti indesiderati.',
                'immagine' => 'raid.png',
                'modalita' => 'Negozio',
                'luogo' => 'Tutti i negozi Crai',
                'inizio' => now()->subDays(5),
                'fine' => now()->addDays(13),
                'sconto' => 'quantita',
                'valore_sconto' => '2x1',
                'created_at' => now()->subDays(6),
                'updated_at' => now()->subDays(6)
            ],
            [
                'idAzenda' => 9,
                'titolo' => 'Heineken, Original 50 cl',
                'descrizione' => 'Heineken Original 50 cl è una birra lager premium dal sapore distintivo e rinfrescante. Con la sua bottiglia da 50 cl, è perfetta per i momenti di condivisione con gli amici o per godersi un momento di relax. Goditi il gusto classico e l\'esperienza autentica di Heineken con questa bevanda di qualità.',
                'immagine' => 'birra.png',
                'modalita' => 'Online',
                'luogo' => 'Store online Esselunga',
                'inizio' => now()->subDays(3),
                'fine' => now()->addDays(18),
                'sconto' => 'prezzo_fisso',
                'valore_sconto' => '0,99',
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3),
            ],
            [
                'idAzenda' => 9,
                'titolo' => 'Esselunga Top, Tagliatelle sfoglia rustica 250 g',
                'descrizione' => 'Le Tagliatelle sfoglia rustica Esselunga Top sono un delizioso formato di pasta fresca, realizzato con ingredienti di alta qualità e una ricetta tradizionale. Grazie alla loro consistenza rustica e alla sfoglia sottile, queste tagliatelle offrono un\'esperienza culinaria autentica e saporita. Perfette da abbinare a salse ricche e condimenti gustosi, sono ideali per creare piatti di pasta raffinati e appaganti.',
                'immagine' => 'pasta.png',
                'modalita' => 'Negozio',
                'luogo' => 'Tutti i negozi Esselunga',
                'inizio' => now(),
                'fine' => now()->addDays(14),
                'sconto' => 'quantita',
                'valore_sconto' => '2x1',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5)
            ],
            [
                'idAzenda' => 10,
                'titolo' => 'Cameo Muu Muu Vaniglia 4 x 125 g',
                'descrizione' => 'Il Cameo Muu Muu Vaniglia è un delizioso dessert al gusto di vaniglia, confezionato in pratiche porzioni da 125 g. La sua consistenza cremosa e il gusto intenso soddisferanno la tua voglia di dolcezza in ogni morso. Ideale per un momento di piacere goloso da gustare da solo o da condividere con gli amici.',
                'immagine' => 'muu.png',
                'modalita' => 'Online',
                'luogo' => 'Store online Si con Te',
                'inizio' => now()->addDays(5),
                'fine' => now()->addDays(15),
                'sconto' => 'prezzo_fisso',
                'valore_sconto' => '1,99',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAzenda' => 10,
                'titolo' => 'Santa Rosa Arance 350 g',
                'descrizione' => 'La marmellata Santa Rosa Arance da 350 g è un\'esplosione di gusto e freschezza. Preparata con arance di alta qualità, offre un sapore autentico e vibrante che delizia il palato. Con la sua consistenza morbida e la dolcezza perfettamente bilanciata, questa marmellata è ideale per spalmare su pane tostato, croissant o per arricchire yogurt e dessert.',
                'immagine' => 'marmellata.png',
                'modalita' => 'Negozio',
                'luogo' => 'Tutti i negozi Si con Te',
                'inizio' => now()->subDays(5),
                'fine' => now()->addDays(20),
                'sconto' => 'quantita',
                'valore_sconto' => '2x1',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5)
            ],
            [
                'idAzenda' => 11,
                'titolo' => 'Ferrero Rocher White 4 x 50 g',
                'descrizione' => 'Il Gelato Ferrero Rocher White è una deliziosa prelibatezza composta da quattro porzioni da 50 g ciascuna. Questa deliziosa variante di gelato presenta un sapore irresistibile di cioccolato bianco arricchito con pezzi croccanti di nocciole tostate, creando un\'esperienza gustativa unica. Il mix di ingredienti pregiati e la cremosità del gelato offrono un piacere indulgente per i veri amanti del cioccolato.',
                'immagine' => 'ferrerogelato.png',
                'modalita' => 'Online',
                'luogo' => 'Store online Auchan',
                'inizio' => now(),
                'fine' => now()->addDays(15),
                'sconto' => 'prezzo_fisso',
                'valore_sconto' => '3,49',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAzenda' => 11,
                'titolo' => 'Capitan Findus 18 Bastoncini con 100% Filetti di Merluzzo 450 g',
                'descrizione' => 'I Filetti di Merluzzo sono un delizioso prodotto ittico confezionato da Findus. Ogni bastoncino è realizzato interamente con filetti di merluzzo di alta qualità, offrendo un sapore autentico e una consistenza croccante. La confezione da 450 g contiene 18 bastoncini, perfetti per un pasto gustoso e conveniente.',
                'immagine' => 'findus.png',
                'modalita' => 'Negozio',
                'luogo' => 'Tutti i negozi Auchan',
                'inizio' => now()->subDays(5),
                'fine' => now()->addDays(20),
                'sconto' => 'quantita',
                'valore_sconto' => '3x2',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5)
            ],
            [
                'idAzenda' => 12,
                'titolo' => 'Carrefour 10+10pz Pile AA stilo',
                'descrizione' => 'Le pile AA stilo di Carrefour sono la scelta perfetta per alimentare i tuoi dispositivi elettronici. Questo pacchetto contiene 10 pile AA di alta qualità, offrendoti un totale di 20 pile per garantire una lunga durata e prestazioni affidabili. Con Carrefour, puoi essere sicuro di avere l\'energia necessaria per i tuoi dispositivi quando ne hai bisogno.',
                'immagine' => 'pile.png',
                'modalita' => 'Online',
                'luogo' => 'Store online Carrefour',
                'inizio' => now(),
                'fine' => now()->addDays(30),
                'sconto' => 'prezzo_fisso',
                'valore_sconto' => '5,99',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAzenda' => 12,
                'titolo' => 'Hasbro Gaming Cluedo Classic',
                'descrizione' => 'Hasbro Gaming Cluedo Classic è una versione intramontabile del famoso gioco da tavolo di mistero. I giocatori si immergono in una scena del crimine e devono scoprire l\'assassino, l\'arma del delitto e il luogo in cui è avvenuto il misfatto. Con personaggi iconici, stanze suggestive e indizi da decifrare, Cluedo Classic offre un\'esperienza di gioco avvincente e stimolante per tutta la famiglia.',
                'immagine' => 'cluedo.png',
                'modalita' => 'Negozio',
                'luogo' => 'Tutti i negozi Carrefour',
                'inizio' => now()->subDays(2),
                'fine' => now()->addDays(14),
                'sconto' => 'percentuale',
                'valore_sconto' => 15,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5)
            ],
            [
                'idAzenda' => 13,
                'titolo' => 'T-shirt adicolor classics 3-stripes',
                'descrizione' => 'La T-shirt Adicolor Classics 3-Stripes è un capo di abbigliamento iconico che combina stile e versatilità. Realizzata con un tessuto leggero e morbido, presenta il classico design a tre strisce sulle maniche e un taglio moderno che si adatta a qualsiasi outfit. Perfetta per un look casual e sportivo, questa T-shirt è un must-have per ogni guardaroba.',
                'immagine' => 'tadidas.png',
                'modalita' => 'Online',
                'luogo' => 'Store online Adidas',
                'inizio' => now(),
                'fine' => now()->addDays(15),
                'sconto' => 'prezzo_fisso',
                'valore_sconto' => '24,99',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAzenda' => 13,
                'titolo' => 'Scarpe Stan Smith',
                'descrizione' => 'Le scarpe Stan Smith sono un\'icona intramontabile dello stile casual. Caratterizzate dal classico design minimalista con tomaia in pelle bianca, queste sneakers sono dotate di dettagli verdi sul tallone e di una suola in gomma per un comfort duraturo. Perfette per ogni occasione, le Stan Smith sono un must-have per gli amanti della moda.',
                'immagine' => 'stan.png',
                'modalita' => 'Negozio',
                'luogo' => 'Tutti i negozi Adidas',
                'inizio' => now()->subDays(5),
                'fine' => now()->addDays(20),
                'sconto' => 'percentuale',
                'valore_sconto' => 15,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5)
            ],
            [
                'idAzenda' => 14,
                'titolo' => 'Nike Air Force 1 \'07',
                'descrizione' => 'Le Nike Air Force 1 \'07 sono un\'iconica scarpa da basket reinterpretata in chiave moderna. Caratterizzate da una tomaia in pelle premium e una suola ammortizzata, offrono comfort e resistenza per tutto il giorno. Con il loro design classico e versatile, sono un must-have per gli amanti dello stile streetwear.',
                'immagine' => 'af1.png',
                'modalita' => 'Online',
                'luogo' => 'Store online Nike',
                'inizio' => now(),
                'fine' => now()->addDays(20),
                'sconto' => 'prezzo_fisso',
                'valore_sconto' => '119,99',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAzenda' => 14,
                'titolo' => 'LeBron XX',
                'descrizione' => 'LeBron XX è l\'ultima aggiunta alla linea di scarpe da basket di LeBron James. Queste scarpe sono progettate per offrire una combinazione di stile, comfort e prestazioni superiori in campo. Con materiali di alta qualità, ammortizzazione reattiva e una suola aderente, le LeBron XX sono la scelta ideale per gli atleti che cercano il massimo supporto durante il gioco.',
                'immagine' => 'lebron.png',
                'modalita' => 'Negozio',
                'luogo' => 'Tutti i negozi Nike',
                'inizio' => now()->subDays(2),
                'fine' => now()->addDays(18),
                'sconto' => 'percentuale',
                'valore_sconto' => 20,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2)
            ],
            [
                'idAzenda' => 15,
                'titolo' => 'Bold OBEY classic t-shirt',
                'descrizione' => 'La maglietta Bold Obey Classic è un capo iconico che si distingue per il suo stile semplice e deciso. Realizzata con materiali di alta qualità, offre un comfort ottimale e una vestibilità perfetta. Il logo Obey sul petto dona un tocco di originalità e rende questa maglietta un must-have per gli amanti dello streetwear.',
                'immagine' => 't-shirtobey.png',
                'modalita' => 'Online',
                'luogo' => 'Store online Obey',
                'inizio' => now(),
                'fine' => now()->addDays(15),
                'sconto' => 'prezzo_fisso',
                'valore_sconto' => '34,99',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAzenda' => 15,
                'titolo' => 'OBEY icon extra heavy pullover hood',
                'descrizione' => 'L\'Icon Extra Heavy Pullover Hood è un capo d\'abbigliamento resistente e versatile, ideale per affrontare le giornate più fredde. Realizzato con un tessuto extra pesante, questo cappuccio offre un calore eccezionale e una protezione affidabile dagli elementi. Con il suo design classico e la sua costruzione di alta qualità, è perfetto per chi cerca comfort e stile duraturi.',
                'immagine' => 'felpaobey.png',
                'modalita' => 'Negozio',
                'luogo' => 'Tutti i negozi Obey',
                'inizio' => now()->addDays(5),
                'fine' => now()->addDays(20),
                'sconto' => 'percentuale',
                'valore_sconto' => 15,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5)
            ],
            [
                'idAzenda' => 16,
                'titolo' => 'Vans OLD SKOOL',
                'descrizione' => 'Le Vans Old Skool sono un\'icona intramontabile dello stile urbano. Queste scarpe da skate presentano una silhouette classica con una tomaia in tela resistente e pelle scamosciata, una banda laterale distintiva e la suola waffle in gomma per una trazione superiore. Perfette per coloro che cercano un look casual e cool.',
                'immagine' => 'vans.png',
                'modalita' => 'Online',
                'luogo' => 'Store online Vans',
                'inizio' => now(),
                'fine' => now()->addDays(15),
                'sconto' => 'prezzo_fisso',
                'valore_sconto' => '79,99',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAzenda' => 16,
                'titolo' => 'Cappellino da pescatore RETROSPECTATOR SPORT',
                'descrizione' => 'Il cappellino da pescatore Retrospectator Sport è un accessorio versatile e alla moda. Realizzato con materiali di alta qualità, offre una protezione solare ottimale durante le attività all\'aperto. Il suo design retrò e sportivo lo rende perfetto per gli amanti dello stile vintage e degli sport all\'aria aperta.',
                'immagine' => 'cappellovans.png',
                'modalita' => 'Negozio',
                'luogo' => 'Tutti i negozi Vans',
                'inizio' => now()->subDays(7),
                'fine' => now()->addDays(18),
                'sconto' => 'prezzo_fisso',
                'valore_sconto' => '34,99',
                'created_at' => now()->subDays(8),
                'updated_at' => now()->subDays(8)
            ],
            [
                'idAzenda' => 17,
                'titolo' => 'Giubbotto effetto pelle',
                'descrizione' => '',
                'immagine' => 'giubb.png',
                'modalita' => 'Online',
                'luogo' => 'Store online Zara',
                'inizio' => now(),
                'fine' => now()->addDays(15),
                'sconto' => 'prezzo_fisso',
                'valore_sconto' => '39,99',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAzenda' => 17,
                'titolo' => 'Fields at nightfall 100 ml',
                'descrizione' => 'Fields at Nightfall è un affascinante profumo da 100 ml che cattura l\'essenza della notte. Con note di testa di agrumi vivaci e freschi, si evolve verso un cuore floreale delicato e si fonde con un fondale sensuale di legni e muschio. Questo profumo incantevole è la scelta perfetta per coloro che desiderano lasciare un\'impressione duratura e misteriosa.',
                'immagine' => 'profzara.png',
                'modalita' => 'Negozio',
                'luogo' => 'Tutti i negozi Zara',
                'inizio' => now()->subDays(5),
                'fine' => now()->addDays(20),
                'sconto' => 'quantita',
                'valore_sconto' => '2x1',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5)
            ],
            [
                'idAzenda' => 18,
                'titolo' => 'Shorts in jersey Essentials uomo',
                'descrizione' => 'Gli shorts in jersey Essentials da uomo di Puma sono l\'abbigliamento essenziale per un comfort e uno stile casual. Realizzati in morbido tessuto jersey, offrono una vestibilità comoda e leggera. Ideali per l\'allenamento o il tempo libero, questi shorts rappresentano una scelta versatile e di qualità per ogni guardaroba maschile.',
                'immagine' => 'shortspuma.png',
                'modalita' => 'Online',
                'luogo' => 'Store online Puma',
                'inizio' => now(),
                'fine' => now()->addDays(20),
                'sconto' => 'prezzo_fisso',
                'valore_sconto' => '19,99',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAzenda' => 18,
                'titolo' => 'PUMA Caven 2.0',
                'descrizione' => 'Le PUMA Caven 2.0 sono scarpe da ginnastica progettate appositamente per i bambini. Queste scarpe combinano stile e comfort, offrendo una calzata leggera e ammortizzata per supportare i piedi in movimento.',
                'immagine' => 'scarpepuma.png',
                'modalita' => 'Negozio',
                'luogo' => 'Tutti i negozi Puma',
                'inizio' => now()->addDays(3),
                'fine' => now()->addDays(25),
                'sconto' => 'percentuale',
                'valore_sconto' => 35,
                'created_at' => now()->subDays(4),
                'updated_at' => now()->subDays(4)
            ],
        ]);

//        User::factory()->admin()->create();
//        User::factory()->staff()->create();
//        User::factory()->user()->create();
//
//        Faq::factory()->count(6)->create();
//
//        Azienda::factory()->count(18)->create();
//
//        Azienda::all()->each(function ($azienda) {
//            $azienda->promozioni()->saveMany(
//                Promozione::factory()->count(2)->make()
//            );
//        });
//
//        Promozione::all()->each(function ($promozione) {
//            if($promozione->inizio <= now()) {
//                $promozione->coupon()->save(
//                    Coupon::factory()->create(['idPromozione' => $promozione->idPromozione])
//                );
//            }
//        });

    }
}
